name: Trigger auto deployment for demo-container

env:
  AZURE_CONTAINER_APP_NAME: demo-container
  AZURE_GROUP_NAME: myresourcegroup
  AZURE_CONTAINER_ENV: my-container-env # Make sure this exists
  CONTAINER_PORT: 80

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Lowercase repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt

            echo "Checking if container app exists..."
            if az containerapp show --name $AZURE_CONTAINER_APP_NAME --resource-group $AZURE_GROUP_NAME &>/dev/null; then
              echo "Updating existing container app..."
              az containerapp update \
                --name $AZURE_CONTAINER_APP_NAME \
                --resource-group $AZURE_GROUP_NAME \
                --image ghcr.io/${{ env.REPO }}:${{ github.sha }} \
                --cpu 2 \
                --memory 4Gi
            else
              echo "Creating new container app..."
              az containerapp create \
                --name $AZURE_CONTAINER_APP_NAME \
                --resource-group $AZURE_GROUP_NAME \
                --environment $AZURE_CONTAINER_ENV \
                --image ghcr.io/${{ env.REPO }}:${{ github.sha }} \
                --target-port $CONTAINER_PORT \
                --ingress external \
                --cpu 2 \
                --memory 4Gi \
                --registry-server ghcr.io \
                --registry-username ${{ github.actor }} \
                --registry-password ${{ secrets.PAT }}
            fi
